### ISSUE TITLE
Nucleus Channel

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-FISH#1]
Hi @Mava04,

What is the typical use-case of the plugin?

1. Do people always have three channels, with two channels containing spots and one channel containing the nucleus?
2. Are there always two channels with spots? Or could there also be three channels with spots?

**Comment by Mava04** [comment]
Hi @tischi ,
the channels are usually either 3 as you described, or 4 if they want to include an additional FISH probe as a "control probe". The distance from the control probe to either probe 1 or 2 is supposed to be constant. If you include the control probe, there are 3 channels with spots, plus the channel with the nucleus. In my (very little) experience, the most common setting is the 3-channel one. 

What might change the most is the number of spots that people expect to see in each nucleus. For example, in tumor tissue they often expect to see the probe hybridize at more than 1 locus per haplotype. But most of the times they just want the counts per nucleus here, distances would not matter that much.

**Comment by tischi** [comment]
Thanks!
