### ISSUE TITLE
Colour spots

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-FISH#12]
We would need to store what channels are the spots created on. 
But I think the fastest way would be to directly use the MANUAL_COLOR feature. Here you just specify what color you want to use, specified as an `int`.

https://github.com/trackmate-sc/TrackMate/blob/master/src/main/java/fiji/plugin/trackmate/features/manual/ManualSpotColorAnalyzerFactory.java

It's one of the lesser known feature of TrackMate but could be a perfect fit if you are ok to specify color 'manually' in your code.

![Screenshot 2023-06-07 at 12 59 23](https://github.com/tischi/fiji-plugin-FISH/assets/3583203/d4df980a-d0e6-4915-ae9b-733b250a6ad6)

_Originally posted by @tinevez in https://github.com/tischi/fiji-plugin-FISH/issues/11#issuecomment-1580529939_

**Comment by tischi** [comment]
@tinevez I need your help; I don't know how to use your suggestion above.

I have a feeling it should go somewhere in the code that [follows here](https://github.com/tischi/fiji-plugin-FISH/blob/29f63cd3e2ecccd810721e542dc01313e154c99e/src/main/java/de/embl/cba/fish/SegmentationOverlay.java#L126) but I really don't know where to start....

Essentially I don't understand how to use `ManualSpotColorAnalyzerFactory` in my code.

**Comment by tischi** [comment]
I [think I did it](https://github.com/tischi/fiji-plugin-FISH/blob/56d1e2c672d273ff8cfc817ca2b04f34dda5eaa8/src/main/java/de/embl/cba/fish/SegmentationOverlay.java#L149) but all spots are still painted in magenta...

Do I have to "activate" the colouring somewhere?

**Comment by tinevez** [comment]
Yes! It's done when you prepare the view:
You would specify to color the spots using the manual spot color.
Like this:

```java
DisplaySettings ds = DisplaySettings.defaultStyle();
ds.setTrackVisible( false );
ds.setSpotVisible( true );
ds.setSpotDisplayRadius( 2. );
ds.setHighlightColor( Color.BLUE );
ds.setSpotColorBy( TrackMateObject.SPOTS, ManualSpotColorAnalyzerFactory.FEATURE );
```
(the last one is important)

Then you pass the `DisplaySettings` `ds` to the view when you create it:

```java
final HyperStackDisplayer view = new HyperStackDisplayer( model, selectionModel, imp, ds );
view.render();
```

If you modify `ds` *after* creating the view, the view will be updated.

**Comment by tischi** [comment]
Yeah, that works! Thank you so much ❤️ !

<img width="643" alt="image" src="https://github.com/tischi/fiji-plugin-FISH/assets/2157566/f04fb8a1-7a3e-4b69-b8ce-d2ea9645629e">

**Comment by tischi** [comment]
Maybe interesting for you: I also managed now to colour the spots in the same colour as the channel of the image.

```
    private Map< Integer, Color > createChannelIndexToColorMap()
    {
        final CompositeImage compositeImage = ( CompositeImage ) (imp);
        final int nChannels = compositeImage.getNChannels();
        Map< Integer, Color > channelIndexToColor = new HashMap<>();
        final LUT[] luts = compositeImage.getLuts();
        for ( int channelIndex = 0; channelIndex < nChannels; channelIndex++ )
        {
            IndexColorModel cm = luts[ channelIndex ];
            int index = cm.getMapSize() - 1;
            int r = cm.getRed(index);
            int g = cm.getGreen(index);
            int b = cm.getBlue(index);
            final Color color = new Color( r, g, b );
            channelIndexToColor.put( channelIndex+1, color );
        }
        return channelIndexToColor;
    }
```
