### ISSUE TITLE
Channel Config

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-FISH#2]
@Mava04

I would like to show below dialog in the beginning to configure the channels. 
Does that make sense? How could it be improved?

![image](https://user-images.githubusercontent.com/2157566/78469053-8ce81b80-771d-11ea-8050-603aa17432e0.png)

**Comment by tischi** [comment]
> I think it's very clear. I was wondering if it is worth having the chance to add one more channel (not for us, just in case other users want to include a control probe)

@Mava04 
This user interface will automatically have the correct amount of channels. So, if you start the plugin with a four channel image, it would have four drop down menus. Is that OK then?

**Comment by Mava04** [comment]
Yes, great

**Comment by tischi** [comment]
Ok, I will implement this then!
